### ISSUE TITLE
Data flattening not working from mongo to bigquery

### ISSUE THREAD

**Issue by ZuSe** [transferwise/pipelinewise-tap-mongodb#109]
I am trying to replicate my mongo database to bigquery. 
For further analytics it would be important to have the whole document unspanned in big query or at least use the RECORD fields. 
However it seems that the data_flattening setting has no impact.
The create bigquery schema looks like this: 

![image](https://github.com/transferwise/pipelinewise-tap-mongodb/assets/522403/b7c8a78e-bff4-47ca-a9ae-0e28e77c0d4f)

My configuration for the mongo-tap is this
```

# ------------------------------------------------------------------------------
# Destination (Target) - Target properties
# Connection details should be in the relevant target YAML file
# ------------------------------------------------------------------------------
target: "bigquery"                                              # ID of the target connector where the data will be loaded
batch_size_rows: 1000                                           # Batch size for the stream to optimise load performance
stream_buffer_size: 256                               # In-memory buffer size (MB) between taps and targets for asynchronous data pipes
default_target_schema: "test"             # Optional: Default target schema where the data will be loaded
add_metadata_columns: true
data_flattening_max_level: 5
#default_target_schema_select_permission:                       # Optional: Grant SELECT on schema and tables that created
#  - grp_power
#batch_wait_limit_seconds: 3600                     # Optional: Maximum time to wait for `batch_size_rows`. Available only for snowflake target.



# ------------------------------------------------------------------------------
# Source to target Schema mapping
# ------------------------------------------------------------------------------
schemas:
  - source_schema: "0"                                  # Must be same name as dbname
    target_schema: "test"            # schema where the data will be loaded
    data_flattening_max_level: 5
#    target_schema_select_permissions:                          # Optional: Grant SELECT on schema and tables that created
#      - grp_stats

    # Available replication methods: FULL_TABLE & LOG_BASED
    # Default replication method is LOG_BASED
    tables:
      - table_name: "schedules"
        replication_method: "FULL_TABLE"
      - table_name: "tasks"
        replication_method: "FULL_TABLE"
      - table_name: "patient"
        replication_method: "FULL_TABLE"


```
